// Generates supabase/installation.sql: all migrations in order, then the game rules, in a single file.
// Usage: node tools/installation.mjs > supabase/installation.sql
// To install or update the database: run this one file in Supabase (SQL Editor). Safe to re-run.
import { readFileSync, readdirSync } from 'node:fs';
const dir = new URL('../supabase/migrations/', import.meta.url);
const files = readdirSync(dir).filter(f => f.endsWith('.sql')).sort();
const out = [
  '-- FULL INSTALLATION of the Ether Mines database. FILE GENERATED by tools/installation.mjs: do not edit by hand.',
  '-- Contains: ' + files.join(', ') + ', then rules.sql.',
  '-- Run all at once in Supabase (SQL Editor). Safe to re-run. To start from scratch: reset.sql first.',
  '',
];
for (const f of files) out.push(`-- ════════════════ ${f} ════════════════`, readFileSync(new URL(f, dir), 'utf8').trimEnd(), '');
out.push('-- ════════════════ rules.sql ════════════════', readFileSync(new URL('../supabase/rules.sql', import.meta.url), 'utf8').trimEnd(), '');
console.log(out.join('\n'));
